namespace SCSE.ClinicalComponents.Blz;

using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
public static class SCSEIcons
{
    public static class Administrative
    {
        public static readonly string CostosInforme = "icon-InformesCostos";
        public static readonly string Costos = "icon-Costos";
        public static readonly string PrimeraCita = "icon-PrimeraCita";
        public static readonly string MasCitas01 = "icon-MasCitas";
        public static readonly string MasCitas02 = "icon-MasCitasR";
        public static readonly string Citas = "icon-Citas";
        public static readonly string CitasGrupales = "icon-CitasGrupales";
        public static readonly string CitaConfirmar = "icon-ConfirmarCita";
        public static readonly string AsignarCita = "icon-AsignarCita";
        public static readonly string CitaCancelar = "icon-CancelarCita";
        public static readonly string CitaEditar = "icon-EditarCita";
        public static readonly string CitaEspecial = "icon-CitaEspecial";
        public static readonly string CitaGrupal = "icon-CitaGrupalInd";
        public static readonly string Reprogramar = "icon-Reprogramar";
        public static readonly string AgendaMenu = "icon-TableroMenu";
        public static readonly string AgendaDias = "icon-CDias";
        public static readonly string AgendaMeses = "icon-CMeses";
        public static readonly string AgendaMulti = "icon-Multiagenda";
        public static readonly string AgendaDuplicar = "icon-Duplicar";
        public static readonly string AgendaBloquear = "icon-Bloquear1";
        public static readonly string AgendaDesbloquear = "icon-Desbloquear";
        public static readonly string AgendaNovedad = "icon-NovedadAgenda";
        public static readonly string AgendaIncumplida = "icon-Incumplir";
        public static readonly string AgendaPeriodica = "icon-Periodicas";
        public static readonly string NoPBS = "icon-NOPBS";
        public static readonly string OrdenesMedicas = "icon-OrdenesMedicas";
        public static readonly string Disponibilidad = "icon-Disponibilidad";
        public static readonly string SeguimientoPAE01 = "icon-SeguimientoPAE";
        public static readonly string SeguimientoPAE02 = "icon-HSeguimientoPAE";
        public static readonly string ListaEspera = "icon-Lista-espera";
        public static readonly string Indicadores = "icon-Indicadores";
    }

    public static class Clinical
    {
        public static readonly string SignosVitales = "icon-SignosVitales";
        public static readonly string Enfermeria = "icon-Enfermeria";
        public static readonly string Notas01 = "icon-Observaciones";
        public static readonly string Notas02 = "icon-ObservacionesH";
        public static readonly string Toxicidades = "icon-Toxicidades";
        public static readonly string Protocolo = "icon-Protocolo";
        public static readonly string Cuidadores = "icon-Cuidadores";
        public static readonly string SalaCirugia = "icon-AccesoriosT";
        public static readonly string Teleconsulta = "icon-Teleconsulta";
        public static readonly string SalaQuirofano = "icon-SalaQuirofano";
        public static readonly string SalaProcedimientos = "icon-SalaProcedimientos";
        public static readonly string Recurso = "icon-Recurso";
        public static readonly string Preconsulta = "icon-Preconsulta";
        public static readonly string Profesional = "icon-Profesional";
        public static readonly string Especialidad = "icon-Especialidad";
        public static readonly string AnalisisResultados = "icon-AnalisisR";
        public static readonly string AntecedentesMedicos = "icon-AntecedentesM";
        public static readonly string Antecedentes = "icon-Antecedentes";
        public static readonly string PlanMedico = "icon-PlanM";
        public static readonly string Escalas = "icon-Escalas";
        public static readonly string ExamenFisico = "icon-ExamenF";
        public static readonly string RevisionSistemas = "icon-RevisionS";
        public static readonly string Consentimiento = "icon-Consentimiento";
        public static readonly string Anticoagulante = "icon-Anticoagulante";
        public static readonly string Medicamento = "icon-MedAlto";
        public static readonly string MedicamentoAltoCosto = "icon-AltoCosto";
        public static readonly string MedicamentoControl = "icon-DeControl";
        public static readonly string MedicamentoNoPOS = "icon-NoPOS";
        public static readonly string MedicamentoMas = "icon-MediMas";
        public static readonly string Psicofarmacos = "icon-Psicofarmacos";
        public static readonly string Antibiotico = "icon-Antibiotico";
        public static readonly string MIPRES = "icon-MIPRES";
        public static readonly string Prerrogativa = "icon-Prerrogativa";
        public static readonly string Prioridad = "icon-Prioridad";
        public static readonly string Historico = "icon-Historico";
        public static readonly string Materna = "icon-Materna";
    }


    public static class Commons
    {
        public static readonly string FlechaAbajo = "icon-FlechaAbajo";
        public static readonly string FlechaDerecha = "icon-FlechaD";
        public static readonly string FlechaArriba = "icon-FlechaA";
        public static readonly string FlechaIzquierda = "icon-FlechaI";
        public static readonly string Ayuda01 = "icon-Ayuda";
        public static readonly string Ayuda02 = "icon-AyudaMenu";
        public static readonly string Guardar = "icon-Guardar";
        public static readonly string Cerrar = "icon-Cerrar";
        public static readonly string Check01 = "icon-Check";
        public static readonly string Check02 = "icon-CheckC";
        public static readonly string Home = "icon-Home";
        public static readonly string Info = "icon-Info";
        public static readonly string Mas = "icon-Mas";
        public static readonly string Eliminar = "icon-Eliminar";
        public static readonly string Detalle01 = "icon-MasDetalle";
        public static readonly string Detalle02 = "icon-Detalle02";
        public static readonly string Detalle03 = "icon-DetalleH";
        public static readonly string Editar01 = "icon-Editar";
        public static readonly string Editar02 = "icon-Editar02";
        public static readonly string Admiracion = "icon-Admiracion";
        public static readonly string Salir = "icon-Salir";
        public static readonly string Configuracion = "icon-Configura";
        public static readonly string UsuarioMasculino = "icon-UsuarioMasculino";
        public static readonly string UsuarioFemenino = "icon-UsuarioFemenino";
        public static readonly string UsuarioAgregar01 = "icon-AgregarPaciente";
        public static readonly string UsuarioAgregar02 = "icon-ConProfesional";
        public static readonly string UsuarioEditar = "icon-EditarPaciente";
        public static readonly string UsuarioCheck = "icon-Usuario01";
        public static readonly string UsuarioTablero = "icon-UsuarioTablero";
        public static readonly string UsuarioSoporte = "icon-Usuario02";
        public static readonly string UsuarioPaciente = "icon-SinPaciente";
        public static readonly string UsuarioPacienteChat = "icon-PacienteChat";
        public static readonly string UsuarioMedicoChat = "icon-MedicoChat";
        public static readonly string UsuarioMedico = "icon-DocUsuario";
        public static readonly string UsuarioMedicoCambio = "icon-CambioDocUsuario";
        public static readonly string Buscar = "icon-Buscar";
        public static readonly string Firmar = "icon-Firma";
        public static readonly string FirmarDispositivo = "icon-FirmaDispositivo";
        public static readonly string FirmaManual = "icon-FirmaManual";
        public static readonly string Persona = "icon-Persona";
        public static readonly string Imprimir = "icon-Imprimir";
        public static readonly string Borrar = "icon-Borrar";
        public static readonly string Identificacion = "icon-ID";
        public static readonly string Documento01 = "icon-Documento1";
        public static readonly string Documento02 = "icon-Documento";
        public static readonly string DocumentoAgregar01 = "icon-GenerarSol";
        public static readonly string DocumentoAgregar02 = "icon-GenerarSolH";
        public static readonly string DocumentoAdjunto = "icon-Asociados";
        public static readonly string DocumentoBuscar = "icon-Detalle01";
        public static readonly string DocumentoAnular = "icon-AnularSolicitud";
        public static readonly string DocumentoOrdenes = "icon-Ordenes";
        public static readonly string DocumentoRespuesta01 = "icon-Respuesta";
        public static readonly string DocumentoRespuesta02 = "icon-RespuestaH";
        public static readonly string DocumentoSeguimiento01 = "icon-Seguimiento";
        public static readonly string DocumentoSeguimiento02 = "icon-SeguimientoH";
        public static readonly string DocumentoRegistrar01 = "icon-Registro";
        public static readonly string DocumentoRegistrar02 = "icon-RegistroH";
        public static readonly string DocumentoCheck01 = "icon-Autorizacion";
        public static readonly string DocumentoCheck02 = "icon-AutorizacionH";
        public static readonly string DocumentoEditar01 = "icon-ModificarS";
        public static readonly string DocumentoEditar02 = "icon-ModificarSH";
        public static readonly string Mensaje01 = "icon-Mensaje";
        public static readonly string Mensaje02 = "icon-Mensaje2";
        public static readonly string Mensaje03 = "icon-Mensaje3";
        public static readonly string Calendario = "icon-Calendario";
        public static readonly string Texto = "icon-Texto";
        public static readonly string Menu = "icon-Menu";
        public static readonly string Administracion = "icon-Administracion";
        public static readonly string Refrescar = "icon-Refrescar";
        public static readonly string Generar01 = "icon-Generar1";
        public static readonly string Generar02 = "icon-Generar";
        public static readonly string PendienteAval = "icon-PendienteAval";
        public static readonly string Cancelar = "icon-X";
        public static readonly string Pin = "icon-Pin";
        public static readonly string Bloquear = "icon-Bloquear";
        public static readonly string MasInfo = "icon-MasInfo";
        public static readonly string Ampliar = "icon-AmpliarVideoChat";
        public static readonly string Reducir = "icon-ReducirVideoChat";
        public static readonly string Video = "icon-VideoChat";
        public static readonly string SinVideo = "icon-SinVideoChat";
        public static readonly string Microfono = "icon-MicrofonoChat";
        public static readonly string SinMicrofono = "icon-SinMicrofonoChat";
        public static readonly string Llamada = "icon-LlamadaChat";
        public static readonly string Enviar01 = "icon-EnviarChat";
        public static readonly string Enviar02 = "icon-Enviar";
        public static readonly string Enviar03 = "icon-Enviarh";
        public static readonly string Adjuntar = "icon-AdjuntarChat";
        public static readonly string Descargar = "icon-Descargar";
        public static readonly string Importar = "icon-Importar";
        public static readonly string Exportar = "icon-Exportar";
        public static readonly string Alarma01 = "icon-Alarmas";
        public static readonly string Alarma02 = "icon-AlarmasH";
        public static readonly string Mover = "icon-MoverCita";
        public static readonly string Pegar = "icon-PegarCita";
        public static readonly string Linea = "icon-LineaMigaPan";
        public static readonly string OrdenAscendente = "icon-ClasificacionTriage";
        public static readonly string Soporte = "icon-Soporte";
        public static readonly string Permisos = "icon-Permisos-app";
        public static readonly string Perfil = "icon-Perfil";
        public static readonly string Notificacion = "icon-Notificaciones";
        public static readonly string Subir = "icon-Subir";
        public static readonly string Actualizar = "icon-Actualizar";
        public static readonly string Touch = "icon-Touch";
        public static readonly string Cambiar = "icon-Cambiar";
    }
}
